# Generated by Django 3.1.4 on 2020-12-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('goingfrom', models.CharField(max_length=200)),
                ('to', models.CharField(max_length=200)),
                ('date', models.DateField()),
            ],
        ),
    ]
