# Generated by Django 3.1.4 on 2020-12-15 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trains', '0003_newuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='email',
            field=models.EmailField(default=' ', max_length=100),
            preserve_default=False,
        ),
    ]
